[theme]
base = "light"

# Colores Corpus
primaryColor = "#3DA9FC"        # Azul claro (botones, toggles, enlaces)
backgroundColor = "#0B1E3F"     # Azul oscuro (fondo principal)
secondaryBackgroundColor = "#122B4A"  # Azul oscuro un poco más claro (paneles, cards)
textColor = "#FFFFFF"           # Blanco (texto)
font = "sans serif"
